mygalaxy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name ="user"

urlpatterns = [
    path("login",views.login_view,name ="login"),
    path("logout",views.logout_view, name ="logout"),
    path("signup",views.signup_view, name ="signup"),
    path("recording",views.recording_view, name ="recording"),
] 
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    student_id = models.CharField(max_length = 10)
    profile_img = models.ImageField(null =True)

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import redirect
from .models import User
import pyaudio,wave
import pyaudio
import wave
import keyboard
import numpy as np



# Create your views here.
def home_view(request):
    return render(request, "users/home.html")
def login_view(request):
    if request.method == "POST":
        #print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username = username, password =password)
        if user is not None:
            print("인증성공")
            login(request, user)
        else:
            print("인증실패")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method =="POST":
        print(request.POST)
        print(222,request.FILES)
        profile_img = request.FILES["profile_img"]
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]


        user = User.objects.create_user(username, email, password)
        user.last_name = lastname
        user.first_name = firstname
        user.student_id = student_id
        user.profile_img = profile_img
        user.save()

        return redirect("user:login")

    return render(request, "users/signup.html")

def recording_view(request):
    CNT = np.random.randint(0,9999)
    
    if "btn_record" in request.GET:
        
        print("start record")
        audio = pyaudio.PyAudio()
        stream =audio.open(format=pyaudio.paInt16,channels=1,rate =44100,input=True,frames_per_buffer=1024)

        frames =[]
        
        
        while True:
            
            data = stream.read(1024)
            frames.append(data)
        
            if keyboard.is_pressed("ESC"):
                
                print("stop and saving")
                break
            
        stream.stop_stream()
        stream.close()
        audio.terminate()

        sound_file = wave.open(f"voice/myrecording{str(CNT)}.wav","wb")
        sound_file.setnchannels(1)
        sound_file.setsampwidth(audio.get_sample_size(pyaudio.paInt16))
        sound_file.setframerate(44100)
        sound_file.writeframes(b''.join(frames))
        sound_file.close()
        CNT += 1
        

    return render(request, "users/recording.html")

users/templates/users/home.html
홈페이지

<a href ="{% url 'user:login' %}">로그인하러가기</a>

users/templates/users/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'sign.css' %}">
로그인 페이지
<br>
<img src="{% static 'gif_/drunken_su.gif' %}" alt="">

<br>
{% if user.is_authenticated %}
    로그인 성공!
    {{ user.username }} 님 환영합니다.
    <img src="{{ user.profile_img.url }}" alt="">
    <a href ="{% url 'user:logout' %}">로그아웃</a>

    <a href ="{% url 'user:recording' %}">녹음하기</a>
{% else %}
    <form action="" method="POST">
        {% csrf_token %}
        <input name ="username" type="text">
        <input name ="password" type="password">
        <input type="submit" value="로그인">
    </form>
    <a href="{% url 'user:signup' %}">회원가입</a>
{% endif %}

users/templates/users/recording.html
{% load static %}
녹음 하기
<link rel="stylesheet" href="{% static 'recording_style.css' %}">
<form action="" method="GET">
    <p> "spacebar", 버튼 클릭 :녹음
        "ESC" : 저장
        방향키 "->"  : 다음문장 </p>
    <input type ="submit" name = "btn_record" value = "record" default />
    
</form>

users/templates/users/signup.html
{% load static %}
<link rel="stylesheet" href="{% static 'sign.css' %}">
회원가입 페이지
<br>
<img src="{% static 'background.jpg' %}" alt="">
<br>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>아이디</p>
    <input name = "username" type="text">
    <p>비밀 번호</p>
    <input name = "password" type="password">
    <p>성</p>
    <input name = "firstname" type="text">
    <p>이름</p>
    <input name = "lastname" type="text">
    <p>이메일</p>
    <input name = "email" type="text">
    <p>학번</p>
    <input name = "student_id" type="text">
    <p>프로필 사진</p>
    <input name="profile_img" type="file">
    <input type="submit" value="회원가입">
</form>